version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    command: ["run", "--allow-net", "--allow-env", "--allow-read", "src/app.ts"]
