name: Suggestion
description: Propose an idea or general suggestion for this project
title: "[SUGGESTION]: "
labels: ["suggestion", "question"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! Please provide as much detail as possible to help us understand and evaluate your idea.

  - type: textarea
    id: suggestion
    attributes:
      label: What would you like to suggest?
      description: Describe your suggestion or idea in detail.
      placeholder: I suggest that [...]
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why do you think this suggestion is good for the project?
      description: Explain the problem it solves or how it improves the project.
      placeholder: This would help because [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered any alternatives?
      description: If applicable, share any alternative approaches or ideas.
      placeholder: Alternatively, we could [...]
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, related issues, or screenshots here.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this suggestion to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to contribute?
      description: Let us know if you would like to help make this happen!
      options:
        - Yes, I can help implement
        - I can help with reviewing or testing
        - No, I'm just suggesting
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      options:
        - label: I have searched for existing suggestions before creating this one
          required: true
        - label: I have provided sufficient information to explain my suggestion
          required: true
