name: Eslint

on:
  push:
    branches:
      - master # Trigger on pushes to the master branch
  pull_request:
    branches:
      - master # Trigger on pull requests targeting the master branch

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Deno
      - name: Install bun
        uses: oven-sh/setup-bun@v2

      # Step 3: Install dependencies (if needed) and cache them
      - name: Install dependencies
        run: bun install

      # Step 4: Run the linter
      - name: Run linter
        env: ${{ secrets }}
        run: bun run lint
