name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2etests:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Deno
      - name: Install bun
        uses: oven-sh/setup-bun@v2

      # Step 3: Install dependencies (if needed) and cache them
      - name: Install dependencies
        run: bun install

      # Step 4: Run the tests
      - name: Run tests
        env: ${{ secrets }}
        run: bun test
