name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2etests:
    name: E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Bun
      - name: Install bun
        uses: oven-sh/setup-bun@v2

      # Step 3: Install dependencies (if needed) and cache them
      - name: Install dependencies
        run: bun install

      # Step 4: Create PostgreSQL uuid-ossp extension
      - name: Create uuid-ossp extension in PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql "postgres://test:test@localhost:5432/test" -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"

      # Step 5: Run the tests with the DATABASE_URL pointing to the PostgreSQL service
      - name: Run tests
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/test
          PORT: ${{ secrets.PORT }}
          APP_ENV: test
        run: bun drizzle-kit push && bun test
